java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZAAAAA &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZBBBBB &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZCCCCC &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZDDDDD &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZEEEEE &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZFFFFF &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZGGGGG &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZHHHHH &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZIIIII &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZJJJJJ &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZKKKKK &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZLLLLL &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZMMMMM &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZNNNNN &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZOOOOO &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZPPPPP &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZQQQQQ &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZRRRRR &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZSSSSS &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZTTTTT &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZUUUUU &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZVVVVV &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZWWWWW &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZXXXXX &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZYYYYY &

java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZAAAAAA &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZBBBBBB &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZCCCCCC &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZDDDDDD &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZEEEEEE &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZFFFFFF &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZGGGGGG &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZHHHHHH &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZIIIIII &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZJJJJJJ &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZKKKKKK &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZLLLLLL &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZMMMMMM &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZNNNNNN &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZOOOOOO &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZPPPPPP &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZQQQQQQ &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZRRRRRR &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZSSSSSS &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZTTTTTT &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZUUUUUU &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZVVVVVV &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZWWWWWW &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZXXXXXX &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZYYYYYY &

java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZAAAAAAA &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZBBBBBBB &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZCCCCCCC &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZDDDDDDD &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZEEEEEEE &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZFFFFFFF &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZGGGGGGG &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZHHHHHHH &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZIIIIIII &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZJJJJJJJ &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZKKKKKKK &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZLLLLLLL &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZMMMMMMM &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZNNNNNNN &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZOOOOOOO &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZPPPPPPP &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZQQQQQQQ &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZRRRRRRR &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZSSSSSSS &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZTTTTTTT &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZUUUUUUU &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZVVVVVVV &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZWWWWWWW &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZXXXXXXX &
java LokLoader /home/carlos/IdeaProjects/LokLoader/src/ruta5.ok ZYYYYYYY &
